/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Date;
import java.util.List;
import java.util.Scanner;

import org.hibernate.cfg.Configuration;

public class App {
    private static TodoDAO todoDAO;
    public static Scanner scanner;

    public static void main(String[] args) {
        scanner = new Scanner(System.in);
        todoDAO = new TodoDAO();

        menu();

        HibernateUtil.shutdown();
    }

    public static void menu() {
        printMenu();

        char choice;

        try {
            choice = scanner.nextLine().toLowerCase().charAt(0);
        } catch (Exception e) {
            System.out.println("Bad input!\n");
            menu();
            return;
        }

        switch (choice) {
            case 'a':
                var item = new TodoItem();
                item.setTodo();
                item.setDueDate();
                item.setPriority();
                todoDAO.saveTodo(item);
                System.out.println();
                break;
            case 'd':
                System.out.print("What item would you like to delete? (enter id): ");
                int id = scanner.nextInt();
                scanner.nextLine();

                todoDAO.deleteTodo(id);
                System.out.println();
                break;
            case 'p':
                todoDAO.getAllTodo().forEach(System.out::println);
                break;
            case 'q':
                System.out.println("Goodbye!");
                return;
            default:
                System.out.println("Invalid!\n");
                break;
        }

        menu();
    }

    public static void printMenu() {
        System.out.println("[A]dd to do item to list");
        System.out.println("[D]elete item from todo list");
        System.out.println("[P]rint to do items");
        System.out.println("[Q]uit");
        System.out.print("Preform an action: ");
    }
}
