version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: todolist_app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/todolist
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  db_data:

